# -*- coding: utf-8 -*-
"""Merge_Sort_Algorithm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RUzS7R5lumeHyYmIq3gICH5YVrZtQVuU
"""

def Mergesort(arr):
  if len(arr)<=1:
    return arr

  mid = len(arr)//2
  lefthalf = arr[:mid]
  righthalf = arr[mid:]

  sortedLeft = Mergesort(lefthalf)
  sortedRight = Mergesort(righthalf)

  return merge(sortedLeft, sortedRight)

def merge(left , right):
  result = []
  i = 0
  j = 0

  while i < len(left) and j < len(right):
    if left [i]< right[j]:
      result.append (left[i])
      i += 1
    else:
      result.append(right[j])
      j += 1

  result.extend(left[i:])
  result.extend(right[j:])

  return result


Unsorted_Array = [3,7,6,-10,15,23.5,55,-13]
sorted_Array = Mergesort(Unsorted_Array)
print("Sorted Array : ", sorted_Array)

"""Merge Sort Algorithm is actually foloow the **Divide and Conquer** Method . In the very first part of our code we use **Mergesort() **function to Divide the array into the smallest part and then we use **merge()** function to merge the smallest divided part ... then finally we get a  sorted array with Merge sort Algorithm .

"""