# -*- coding: utf-8 -*-
"""quick_sort_using_python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BHRyfhmMHuv5aaXhpt6oXroTFOe9JJyO
"""

#Quick sort algorithm

def QuickSort(arr):
  if len(arr) <= 1:
    return arr

  pivot = arr[-1]
  left = []
  right = []

  for i in range (len(arr)-1):
    if arr[i] < pivot:
      left.append(arr[i])
    else:
      right.append(arr[i])

  return QuickSort(left) + [pivot] + QuickSort(right)

#arr = [8,3,1,7,0,10,2]
#print(QuickSort(arr))

n = int(input("Enter the size of your array:"))
arr = list(map(int,input("Enter the Element : ").split()))
print(QuickSort(arr))